### ISSUE TITLE
Upgrade 2.3 -> 2.4 broke the integration

### ISSUE THREAD

**Issue by bobvandenberge** [auth0-extensions/auth0-gitlab-deploy#31]
I would like to report a: '**regression**'.

After upgrading from version 2.3 to 2.4 our integration stopped working. When the hook gets activated in gitlab, we get a _400_ with the following body:

`Error: Cannot find module 'gitlab@3.4.2'
at Function.Module._resolveFilename (module.js:325:15)
at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:49:27)
at WebtaskModule.require (/data/sandbox/lib/module.js:101:39)
at require (/data/sandbox/lib/module.js:136:21)
at Object.<anonymous> (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:82983)
at t (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:177)
at Object.module.exports.n (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:7344)
at t (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:177)
at Object.<anonymous> (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:56163)
at t (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:177)
at Object.module.exports.e.__esModule.default (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:58275)
at t (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:177)
at Object.module.exports.e.__esModule.default (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:63455)
at t (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:177)
at Object.<anonymous> (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:27201)
at Object.<anonymous> (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:28636)
at t (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:177)
at Object.<anonymous> (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:65703)
at t (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:177)
at /data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:560
at Object.<anonymous> (/data/io/5365e808-2c4d-46f4-ab2c-87eda7af9886/webtask.js:1:571)
at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)
at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)
at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)
at /data/sandbox/lib/compiler.js:231:17
at /data/sandbox/node_modules/async/dist/async.js:3880:24
at replenish (/data/sandbox/node_modules/async/dist/async.js:1011:17)
at /data/sandbox/node_modules/async/dist/async.js:1016:9`

**Comment by bobvandenberge** [comment]
This was our own fault. The error was caused due to an invalid secret. The error code for this could be improved though.
